```{r}
knitr::opts_chunk$set(
    error     = TRUE,     # Ensures that error messages are being shown in the output
    fig.align = "center", # Ensures that all figures are aligned to the centre in the output
    message   = TRUE,     # Display messages generated by R
    warning   = TRUE,     # Display warnings generated by R
    autodep   = TRUE,     # Automatically detects dependencies between chunks and reruns dependent chunks when needed
    cache     = FALSE,    # Disables caching, meaning every time the document is knit, all chunks are re-executed
    results   = "markup", # Displays the output as normal formatted text
    echo      = TRUE     # Ensures that the R code itself is displayed in the document
    #dev       = "svg",    # Graphics output will be in Scalable Vector Graphics (SVG) format
    #out.width = "90%",    # Sets the width of the output image or plot to 90% of the available width 
  #out.extra = "keepaspectratio=true" # Adds extra options to the output, in this case, preserving the aspect ratio of the image or plot
)
```

```{r}
# Maximum allowable size for globals in bytes that can be exported to the parallel workers
mib <- 9000*1024^2
options(future.globals.maxSize = mib)  # 1.5 GiB
```

```{r}
library(here)
```

# Set Up Working Environment

## Load Packages & Functions

```{r}
source(here("Custom R Functions and Scripts", "init_packages.R"))
```

# Configuration

Custom Colours

```{r}
# Custom colors
man_cols <- c("#86b0cc",  "#f3e65d", "#d5c1e7", "#eeb84c", "#82c39e", "#525252","#4d9f6b", "#b3939e", "#e76031", "#e9944b")
names(man_cols) <- c("B_cells", "NK_cells", "monocytes", "T_cells", "neutrophils", "megakaryocytes", "pDCs",
                     "plasma_cells", "progenitor_cells", "NKT_cells")
```
